- eahub/static/styles/profile.css
- templates/eahub/profile.html
Closes https://github.com/rtcharity/hubreboot/issues/54
> 54 feedback profile page

- eahub/static/js/heatmap/heatmap.js
- templates/eahub/home/features.html
- templates/eahub/profile.html
closes https://github.com/rtcharity/hubreboot/issues/57.
> 57 fix bugs

- eahub/static/js/base.js
- eahub/static/styles/profiles.css
- templates/eahub/groups.html
- templates/eahub/profile.html
- templates/eahub/profiles.html
add picture column on profiles table
> 56 add pic column

- eahub/static/styles/profile.css
- eahub/views.py
- groups/models.py
- templates/eahub/group.html
- templates/eahub/maps/profile_link.html
partly implements https://github.com/rtcharity/hubreboot/issues/79
> 79 group info backend to frontend

- eahub/static/styles/banner.css
- eahub/static/styles/base.css
- eahub/static/styles/footer.css
- eahub/static/styles/profile.css
- eahub/urls.py
- templates/base.html
- templates/eahub/group.html
- templates/eahub/groups.html
- templates/eahub/profile.html
- templates/eahub/profiles.html
Experimenting with design 
* slimmer container 
* horizontal menu for laptop
closes #85
> 84 more padding and margins

- eahub/static/js/maps/heatmap.js
- eahub/static/styles/index.css
- eahub/views.py
- templates/eahub/groups.html
- templates/eahub/index.html
- templates/eahub/maps/heatmap.html
> 94 maps on homepage

- eahub/static/scripts/main.js
- eahub/static/styles/main.css
- templates/base.html
> global burger

- templates/eahub/profile.html
> row9: pulled profile image and name more left

- eahub/static/styles/main.css
- eahub/urls.py
- eahub/views.py
- templates/eahub/about.html
addresses #116
This is not done yet:
> add basic about page

- eahub/static/styles/main.css
- templates/eahub/edit_profile_career.html
- templates/eahub/profile.html
> 162 delete profile frontend

- eahub/static/styles/main.css
- templates/registration/password_reset_complete.html
- templates/registration/password_reset_confirm.html
- templates/registration/password_reset_done.html
- templates/registration/password_reset_form.html
> 157 password reset

- Dockerfile
- eahub/build_settings.py
- eahub/settings.py
- requirements.txt
> Fix Whitenoise failure when DEBUG = False

- docker-compose.yml
- eahub/static/styles/main.css
- eahub/urls.py
- eahub/views.py
- templates/403.html
- templates/404.html
- templates/500.html
- templates/base.html
> 155 add 404

- eahub/static/scripts/maps/heatmap.js
- eahub/views.py
> 186 labels for unlocked profiles

- eahub/static/scripts/edit.js
- eahub/static/scripts/main.js
- eahub/static/styles/main.css
- eahub/urls.py
- eahub/views.py
- templates/base.html
- templates/eahub/about.html
- templates/eahub/edit_profile.html
- templates/eahub/privacy_policy.html
- templates/eahub/terms_and_conditions.html
> Privacy policy page

- requirements.txt
This is an attempt at solving #199.
> Install Hiredis

- eahub/static/scripts/form.js
- templates/eahub/edit_profile_cause_areas.html
> show other pledge field only if other is chosen

- eahub/static/scripts/main.js
- eahub/static/styles/main.css
- templates/base.html
> 212 edit button

- templates/base.html
> login buttons dont show on staging page

- docker-compose.yml
- eahub/settings.py
- requirements.txt
> Add Application Insights reporting

- eahub/profiles/views.py
Fixes #282. Don't merge until #240 is fixed.
> Fix /profile/ 500 error

- eahub/base/views.py
> Link to proper URLs of objects in maps

- eahub/config/settings.py
> Send email notifications of broken links

- eahub/profiles/forms.py
> Make email subscription optional

- eahub/templates/base.html
> Change "Fork here" to "View source"

- eahub/base/static/scripts/maps/heatmap.js
- eahub/base/static/styles/main.css
- eahub/templates/base.html
- eahub/templates/eahub/about.html
closes #310 
closes #307 
closes #273
> Pre announcement fixes

- README.md
This only works if all committers are on board with it, so I've added everyone in @rtcharity/tech as a reviewer. Please review at your earliest convenience.
Fixes #324 and #327.
> Specify commit message practices

- eahub/templates/eahub/maps/homepage_map.html
> Make labels on radio buttons on home page clickable

- eahub/templates/registration/signup.html
> Stylistically change privacy note in sign up

- eahub/profiles/models.py
> Add Founders Pledge to Giving Pledges

- eahub/base/models.py
- eahub/config/build_settings.py
- eahub/config/settings.py
- eahub/localgroups/forms.py
- eahub/localgroups/migrations/0003_organisership.py
- eahub/localgroups/models.py
- eahub/localgroups/rules.py
- eahub/localgroups/urls.py
- eahub/localgroups/views.py
- eahub/profiles/models.py
- eahub/requirements.txt
- eahub/templates/eahub/delete_group.html
- eahub/templates/eahub/edit_group.html
- eahub/templates/eahub/group.html
- eahub/templates/eahub/groups.html
Organisers can edit the information of their group, including its list of organisers, and can delete their group. Anyone can create a group.
Fixes #304.
> Create organisership for local groups

- eahub/profiles/views.py
> Fix 500 error when editing membership

- eahub/base/static/scripts/group.js
- eahub/base/static/scripts/main.js
- eahub/base/static/styles/main.css
- eahub/localgroups/urls.py
- eahub/localgroups/views.py
- eahub/templates/eahub/group.html
- eahub/templates/emails/claim_group.html
- eahub/templates/emails/report_group_inactive.html
* closes #308 
* Closes #378 by removing "We don't know who the organisers are" from "claim group" field
> 308 report group as inactive

- eahub/localgroups/views.py
- eahub/templates/emails/claim_group.html
- eahub/templates/emails/claim_group.txt
- eahub/templates/emails/report_group_inactive.html
- eahub/templates/emails/report_group_inactive.txt
> Remove html from admin email

- eahub/profiles/models.py
> Add more Expertise options

- eahub/templates/base.html
- eahub/templates/eahub/index.html
> Make Privacy Policy and Priority Wiki links HTTPS

- eahub/localgroups/models.py
- eahub/profiles/models.py
> Order profiles and groups alphabetically

- eahub/localgroups/forms.py
Due to a CSS problem, the checkbox is misaligned. I've opened #399 instead of trying to fix this now.
Fixes #375.
> Add activity status to group editing form

- eahub/base/static/styles/main.css
- eahub/templates/eahub/edit_group.html
> 399 is active misaligned

- eahub/base/static/styles/main.css
If the answer to [this question](https://github.com/rtcharity/eahub.org/issues/372#issuecomment-472592205) is yes, then this PR should close #372
> Make width of select container smaller

- eahub/base/static/scripts/main.js
- eahub/base/static/styles/main.css
- eahub/templates/eahub/edit_profile_career.html
- eahub/templates/eahub/edit_profile_cause_areas.html
- eahub/templates/eahub/edit_profile_community.html
> 403 multiselect searchable

- docker-compose.yml
- eahub/config/settings.py
- eahub/localgroups/views.py
> Send group related emails to lean@eahub.org 

- eahub/base/static/styles/main.css
- eahub/templates/eahub/about.html
- eahub/templates/eahub/profile.html
> 393 group hyperlink on profile

- eahub/config/settings.py
Reverts #322.
Seems worth giving this another shot and seeing if Yandex is still going to give us a hard time.
Related to #321.
> Revert "Revert "Send email notifications of broken links""

- eahub/profiles/models.py
> Fix 500 error when exporting profile data

- docker-compose.yml
- eahub/config/settings.py
- eahub/profiles/management/commands/profilesfromlegacyhub.py
- eahub/profiles/migrations/0006_profile_legacy_record.py
- eahub/profiles/models.py
- eahub/requirements.txt
Don't run this in production yet, as there are numerous unresolved bugs, including around privacy protections.
Fixes: #330
Fixes: #422
Signed-off-by: Taymon A. Beal <taymon@google.com>
> Create management command to migrate profiles from legacy Hub

- eahub/base/static/scripts/maps/heatmap.js
> 423 profile marker cluster disappear

- eahub/templates/eahub/group.html
> Add other group type

- eahub/base/static/scripts/maps/heatmap.js
- eahub/base/views.py
- eahub/templates/eahub/maps/homepage_map.html
- eahub/templates/eahub/maps/list_page_map.html
- eahub/templates/eahub/profiles.html
> 420 cluster anonymous profiles

- eahub/base/middleware.py
- eahub/config/settings.py
This will hopefully help get us more informative ones.
Part of #321.
> Show X-Forwarded-For header in broken link emails

- eahub/base/views.py
- eahub/config/urls.py
> Redirect from /favicon.ico

- eahub/base/static/styles/main.css
> Add word wrap on profile

- eahub/base/static/styles/main.css
- eahub/templates/eahub/profile.html
- eahub/templates/eahub/profiles.html
> Add label on private profiles

- eahub/base/static/styles/main.css
> Align change of display property with col-md width

- eahub/base/static/scripts/maps/heatmap.js
- eahub/base/static/styles/main.css
> Add bullet points

- eahub/templates/eahub/edit_profile_community.html
> Put available as speaker before topics I speak about

- eahub/templates/eahub/group.html
> Remove N/A and fix bug that showed code rather than organiser name

- eahub/templates/eahub/about.html
> 395 update roadmap

- eahub/base/static/scripts/edit.js
- eahub/base/static/scripts/main.js
- eahub/base/views.py
- eahub/templates/eahub/edit_profile.html
- eahub/templates/eahub/groups.html
- eahub/templates/eahub/maps/homepage_map.html
- eahub/templates/eahub/maps/list_page_map.html
- eahub/templates/eahub/maps/profile_page_map.html
> Fix "undefined" bug on profile maps

- eahub/base/static/scripts/main.js
- eahub/base/static/styles/main.css
- eahub/templates/eahub/about.html
- eahub/templates/eahub/group.html
- eahub/templates/eahub/groups.html
- eahub/templates/eahub/profile.html
- eahub/templates/eahub/profiles.html
Only merge if on #461 we decide to go for allow links in custom text fields
> Add links to custom textfield and refactor some CSS

- eahub/base/static/scripts/maps/heatmap.js
- eahub/templates/eahub/maps/list_page_map.html
> Render missing profiles map

- eahub/base/static/styles/main.css
- eahub/templates/eahub/group.html
- eahub/templates/eahub/profile.html
> 451 and more ux fixes

- eahub/profiles/management/commands/profilesfromlegacyhub.py
- eahub/profiles/models.py
> Import expertise areas from legacy profiles

- eahub/base/static/scripts/maps/heatmap.js
- eahub/base/views.py
> 477 private profiles where no public

- eahub/templates/eahub/profile.html
> Render line breaks from longform text fields

- eahub/templates/eahub/profile.html
> Add organisership to profile

- eahub/templates/base.html
- eahub/templates/eahub/about.html
> Link to feedback site

- eahub/config/settings.py
- eahub/templates/base.html
> 485 no reply address

- eahub/profiles/management/commands/profilesfromlegacyhub.py
- eahub/profiles/models.py
> Import cause areas

- eahub/base/views.py
- eahub/config/urls.py
Fixes: #433
Signed-off-by: Taymon A. Beal <taymon@google.com>
> Login users and redirect to profile edit form on password reset

- eahub/templates/eahub/profile.html
> Fix display of names like MacAskill

- eahub/base/static/scripts/maps/heatmap.js
> 491 profile map

- eahub/base/static/styles/main.css
- eahub/templates/eahub/edit_profile.html
- eahub/templates/eahub/edit_profile_career.html
- eahub/templates/eahub/edit_profile_cause_areas.html
- eahub/templates/eahub/edit_profile_community.html
> Make privacy verbiage simpler and show as text not tooltip

- eahub/base/static/scripts/maps/heatmap.js
adds number of profiles to marker on map, as suggested [here](https://github.com/rtcharity/eahub.org/issues/491#issuecomment-476442861)
closes #491
> Add number of profiles to marker

- eahub/templates/eahub/profile.html
> Fix 500 error with profiles organising one group

- eahub/base/views.py
> Redirect users to profile editor after password reset

- eahub/templates/eahub/profiles.html
> Fix 500 error for anonymous users at /profiles

- eahub/config/build_settings.py
- eahub/config/settings.py
- eahub/requirements.txt
> Check user passwords against the Pwned Passwords database

- eahub/profiles/models.py
- eahub/profiles/views.py
- eahub/templates/eahub/profile.html
> Add N/A for all thre profile panels if no info given

- eahub/templates/accounts/login.html
closes #432 
Don't merge before #436 has been merged.
> Point to reactivation email

- eahub/templates/base.html
> Integrate Smooch

- eahub/profiles/views.py
> Fix 500 error when deleting profile

- eahub/profiles/views.py
> Fix 500 error when deleting profile (really this time)

- eahub/localgroups/views.py
> Fix 500 error when claiming group

- eahub/requirements.txt
Our fork includes a PR, unmerged upstream, that fixes a known bug. See commit history for more details.
Fixes: #553
> Switch to rtcharity fork of django-authtools

- eahub/profiles/forms.py
- eahub/profiles/models.py
> Disallow profile names resulting in problematic slugs

- eahub/templates/base.html
> Switch to the correct Google Analytics ID

- eahub/base/views.py
- eahub/config/urls.py
> Redirect site features from legacy URLs

- eahub/base/views.py
- eahub/config/urls.py
- eahub/templates/robots.txt
> Add robots.txt

- eahub/profiles/models.py
- eahub/profiles/views.py
Also change it from CSV to JSON.
Fixes: #348
> Update data export to include all fields

- eahub/base/static/styles/main.css
> break long names in select lists

- eahub/config/urls.py
> Redirect from legacy URLs to external content pages

- eahub/templates/eahub/group.html
Because this is fixing a critical security vulnerability, I have already deployed it to production, before pushing it to GitHub.
Thanks to @Discordius for responsibly disclosing this.
> Fix persistent XSS on group page

- eahub/templates/account/signup.html
Closes https://github.com/rtcharity/eahub.org/issues/513
> Singup page break UX fix

- eahub/localgroups/forms.py
> Fix 500 error when editing groups

- eahub/templates/base.html
> Remove leading slashes from {% static %} paths

- eahub/profiles/models.py
Closes https://github.com/rtcharity/eahub.org/issues/592
> Adding ALLFED as an organisation

- eahub/profiles/models.py
Closes https://github.com/rtcharity/eahub.org/issues/573
> Adding new cause areas

- eahub/profiles/models.py
Closes https://github.com/rtcharity/eahub.org/issues/646
> Adding Education as a new expertise area

- eahub/base/static/styles/main.css
- eahub/templates/eahub/edit_profile_community.html
> Add info to organisational affiliation field

- eahub/templates/base.html
- eahub/templates/eahub/about.html
Closes https://github.com/rtcharity/eahub.org/issues/554
> Changing hrefs to target="_blank" for feedback.eahub.org

- eahub/config/urls.py
Closes https://github.com/rtcharity/eahub.org/issues/520
> Recreate /newsletter

- eahub/config/urls.py
Closes https://github.com/rtcharity/eahub.org/issues/711
> Fix *template* to .as_view(pattern_name='newsletter')

- eahub/ads.txt
- eahub/templates/ads.txt
> Fix 500 errors on ads.txt

- eahub/base/static/styles/main.css
> Make slogan on landing page white

- eahub/templates/account/login.html
- eahub/templates/base.html
- eahub/templates/eahub/index.html
- eahub/templates/form.html
- eahub/tests/login_test.py
- eahub/tests/signup_test.py
Closes https://github.com/rtcharity/eahub.org/issues/735
> Basic test scenarios for successful sign-up and unsuccessful sign-in

- README.md
Closes https://github.com/rtcharity/eahub.org/issues/713
> Updating the doc

- README.md
> Add browser support policy to README

- eahub/base/exceptions.py
- eahub/base/views.py
- eahub/config/urls.py
- eahub/profiles/views.py
> Abolish 404 emails

- eahub/config/settings.py
- eahub/requirements.txt
> Add Referrer-Policy and Feature-Policy response headers

- eahub/Dockerfile
This makes some things nicer, like setting breakpoints.
> Upgrade to Python 3.7

- README.md
- eahub/base/forms.py
- eahub/base/models.py
- eahub/base/tests/smoke_test.py
- eahub/base/views.py
- eahub/config/settings.py
- eahub/config/urls.py
- eahub/localgroups/rules.py
- eahub/localgroups/urls.py
- eahub/localgroups/views.py
- eahub/profiles/forms.py
- eahub/profiles/migrations/0002_profile_organisational_affiliations.py
- eahub/profiles/migrations/0005_other_fields.py
- eahub/profiles/models.py
- eahub/profiles/urls.py
- eahub/profiles/views.py
- eahub/tests/login_test.py
- eahub/tests/signup_test.py
- fabfile.py
- pyproject.toml
- pytest.ini
- requirements.txt
> Add black autoformatter and enforce in continuous integration

- eahub/base/migrations/0002_create_superusers.py
- eahub/base/views.py
- eahub/config/urls.py
- eahub/profiles/migrations/0008_profile_slug.py
- eahub/profiles/urls.py
- eahub/profiles/views.py
- eahub/templates/account/signup.html
- eahub/templates/base.html
- eahub/templates/eahub/edit_group.html
- eahub/templates/eahub/edit_profile_career.html
- eahub/templates/eahub/edit_profile_cause_areas.html
- eahub/templates/eahub/edit_profile_community.html
- eahub/tests/login_test.py
- requirements.txt
> Enforce PEP 8 naming conventions

- eahub/localgroups/migrations/0003_localgroup_last_edited.py
- eahub/localgroups/models.py
Please migrate and deploy as soon as possible to avoid loss of changes from the upcoming mass entry.
Fixes: #779
> Add last_edited field to LocalGroup

- .gitignore
- requirements.txt
Reverts rtcharity/eahub.org#797
This still doesn't work. I still need to figure out how to fix it.
> Revert "Report test results in Azure Pipelines UI"

- eahub/base/views.py
Replace `x` with human-readable variables, reformat
> Improve readability

- eahub/templates/base.html
> Redirect to previous page after user logs in

- eahub/templates/eahub/group.html
- eahub/templates/eahub/maps/profile_page_map.html
> Fix missing map on group page

- eahub/templates/base.html
> Remove smooch.io from site

- eahub/base/static/scripts/main.js
- eahub/base/static/scripts/profile-edit-image.js
> Fix image change bug

- eahub/base/admin.py
Hopefully this will help fight spam.
> Improve admin interface for User model

- eahub/templates/eahub/group.html
- eahub/templates/eahub/groups.html
- eahub/templates/eahub/profile.html
> Remove messaging on individual and group profiles

- eahub/templates/base.html
> Remove redundant "Log in" and "Sign up" from drop-down menu

- eahub/profiles/forms.py
The column has a not-null constraint, so we need to explicitly specify this value.
> Fix not-null error on sign-up

- eahub/templates/eahub/groups.html
> Delete community column

- eahub/templates/eahub/group.html
> Hide organisers field if there are none

- eahub/templates/eahub/groups.html
> fix bug with location group column

- docker-compose.yml
Adds migration service to docker-compose
> Run migration as part of build process

- docker-compose.yml
Instead of creating separate service for migration, just run migration as part of web service's command
> Simplify docker-compose

- eahub/templates/eahub/index.html
> Remove 2000+ from slogan

- eahub/base/static/styles/main.css
- eahub/templates/eahub/groups.html
- eahub/templates/eahub/profiles.html
> 928 text changes group

- eahub/templates/eahub/edit_group.html
> fix bug not using multiselect on group edit page

- eahub/base/utils.py
- eahub/localgroups/admin.py
- eahub/localgroups/models.py
- eahub/profiles/admin.py
> Group data csv

- eahub/profiles/models.py
> Update areas of expertise

- eahub/base/admin.py
- eahub/config/build_settings.py
- requirements.txt
* Adds [django-admin-rangefilter](https://pypi.org/project/django-admin-rangefilter/) as dependency  
* Adds date filter for date_added and last_login to user profiles in admin panel  
* Adds toggle filter for "public" to user profiles in admin panel
> Enable filtering of users by date added, last login and publicity

- eahub/templates/eahub/report_abuse.html
> prevent report abuse page indexing #1001

- eahub/profiles/models.py
> fix bug with enums

- eahub/profiles/models.py
Initial fix messed up the profiles on search.
Tested locally, looks fine now:
> fix enum/algolia bug

- .dockerignore
- .env
- Dockerfile
- eahub/config/build_settings.py
- eahub/config/settings.py
- eahub/profiles/index.py
- eahub/profiles/models.py
- eahub/templates/eahub/profiles.html
> Add a separate algolia index for testing, fix cause_areas or careers update bug, optimize collectstatic and docker

- eahub/config/build_settings.py
- eahub/config/settings.py
- eahub/templates/eahub/profile.html
- requirements.in
- requirements.txt
* Adds the django package [feature-flags](https://github.com/cfpb/django-flags)   
* Allows for toggling new features, for example, showing them locally and on stage, but not in prod (a [pattern proposed by Martin Fowler](https://martinfowler.com/articles/feature-toggles.html)
> Add feature flags

- eahub/profiles/models.py
- eahub/profiles/views.py
- eahub/templates/eahub/edit_profile_community.html
There is a discussion of which charities to include here: https://github.com/rtcharity/eahub.org/issues/995. I have added all the ones that Vaidehi has listed, but no more.
> Extend & reorder users organizations

- eahub/profiles/models.py
https://stackoverflow.com/questions/65615361/configurationerror-while-using-nominatim-in-jupyter-notebook
> fix the profiles geocoding update

- .env
- eahub/profiles/forms.py
- eahub/templates/account/signup.html
> rollback to recaptcha v2 because we have no v3 fallback

- eahub/base/views.py
can check this working on dev, deployed with messagging feature toggle set to false: https://eahub-dev-815fc48.us.aldryn.io
> Feature toggle messaging page

- eahub/config/build_settings.py
- eahub/config/settings.py
- eahub/profiles/admin.py
- requirements.in
- requirements.txt
I also reordered the admin panel a bit, that's what we usually do for every project since by default django admin isn't user-friendly.
@sebgrebe, would you be able to help with merging it in on Saturday? I can help with moderation tomorrow then. With this patch I also noticed users who were approved by mistake several months ago (they have spam URLs in their summaries)
> profiles: add more fields for easier moderation
