rtcharity/eahub.org

eahub/static/styles/profile.css
templates/eahub/group.html

Implements: https://github.com/rtcharity/hubreboot/issues/79
Some examples:
* [Group with summary; country in key facts](https://eahub.azurewebsites.net/group/96) 
* [Group with summary; organiser and website in key facts](https://eahub.azurewebsites.net/group/97)
* [Group with summary; donations; no key facts](https://eahub.azurewebsites.net/group/116) 
* [Group with more than one organiser in key facts](https://eahub.azurewebsites.net/group/94) 
Remarks
* A couple of fields in the key facts that **were** in the wireframes I didn't implemented as they don't exist in the database
* I've implemented a few fields in the key facts that were **not** in the wireframes, which I implemented as they were in the database and seemed useful

79 group info backend to frontend

---

profiles/migrations/0020_case_insensitive_email.py
profiles/models.py

Also delete all profiles with duplicate emails.
I don't know how to test this since we can't readily repro the original migration.

Make email case-insensitive in the database

---

eahub/config/settings.py

Reverts rtcharity/eahub.org#292
The emails are just uselessly spamming us. If I can figure out how to make them report the end-user IP then they might be useful.
Related to #321.

Revert "Send email notifications of broken links"

---

eahub/base/static/styles/main.css
eahub/config/build_settings.py
eahub/profiles/forms.py
eahub/templates/eahub/delete_profile.html
eahub/templates/eahub/edit_profile.html
eahub/templates/eahub/edit_profile_career.html
eahub/templates/eahub/edit_profile_cause_areas.html
eahub/templates/eahub/edit_profile_community.html
eahub/templates/form.html
eahub/templates/registration/login.html
eahub/templates/registration/signup.html
requirements.txt

addresses #229 
Aim was to replace html for forms by django-crispy forms. Ideally, each form would just be displayed by {{ form | crispy }} in the html.
For a couple of forms, I could not do this because rendering specific fields adequately through Django-crispy-forms proved difficult. In those cases I rendered those fields through html and all others fields in this form through {{ form.FIELDNAME | as_crispy_field }}. Those forms were:
- edit_profile.html. Problematic field: image upload (looks terrible with django forms and I couldn't figure out a non-hacky way to fix that)
- edit_profile_cause_areas.html: Problematic fields: cause areas and giving pledges taken. In django forms, they display the id of the cause area or giving pledge, not their name. Probably fixable, but couldn't figure …

229 django forms

---

docker-compose.yml

None of our processes ever really crash. (Our Python code throws exceptions all the time, of course, but Gunicorn handles them.) Meanwhile, this behavior sometimes causes problems; notably, it was probably responsible for last week's outage during the remigration.

Turn off auto-restart in Docker Compose

---

manage.py

Our officially documented workflow per README.md doesn't require this, but every tutorial and guide on the internet tells people to use it, and some tools like PyCharm expect it to be there, and having it there doesn't hurt anything, so we might as well have it and make everyone's life easier.

Restore manage.py

---

eahub/localgroups/migrations/0002_localgroup_ordering.py
eahub/profiles/migrations/0004_profile_ordering.py

This should have been part of #397, but was omitted accidentally.

Add migrations for local group and profile ordering

---

eahub/base/static/scripts/maps/heatmap.js
eahub/base/static/styles/main.css

partly addresses #420 
Profiles in one location are now available in list on label, rather than spiderfied. Did not apply this to groups as groups are rarely in same position and if they are, we want markers to spiderfy so that user can visually distinguish between active and inactive groups
Once number of anonymous profiles at a location is made available to frontend, this can be easily added to the profiles_at_location variable in heatmap.js to add anonymous profiles to clusters of profiles, which would the fully fix 420.

420 cluster anonymous profiles

---

eahub/base/middleware.py

We already know we broke a bunch of old links, so for now we only want to hear about them if they're affecting real humans.
Part of #321.

Don't email about 404s from Googlebot

---

eahub/templates/registration/password_reset_form.html

- Issue https://github.com/rtcharity/eahub.org/issues/421
- We need a way to auto-fill the email field on the reset-passoword page so we can send mailshots to users to reset their password with little additional effort required on their end
- Added some simple javascript to extract the email address from the url like `https://eahub.org/profile/password_reset/#hello@email.com` and fill in the input field
- Update the email we're sending to old users to include the `#hello@email.com` at the end of the URL

autofill reset email field

---

eahub/base/static/scripts/maps/heatmap.js
eahub/templates/eahub/maps/list_page_map.html

closes #458 
Groups in same location now also displayed in list, rather than spiderfied. Inactive groups are marked by "(inactive)" label after name.

458 several groups in one spot

---

eahub/base/static/scripts/main.js
eahub/base/static/styles/main.css
eahub/templates/eahub/edit_profile.html

closes #347 
- When user has previously chosen image gives option to clear image
- Removes the checkbox for clearing image when user selects an image
- Furthermore, adds a toggle for changing picture if one exists. Previously, users would see immediately "No file chosen" next to "Browse" when they come to edit_profile even if they currently have a picture, which might be confusing

Add clearing picture function

---

eahub/templates/base.html

closes #468, in particular [this](https://github.com/rtcharity/eahub.org/issues/468#issuecomment-476038917)

change footer

---

eahub/profiles/admin.py
eahub/profiles/management/commands/profilesfromlegacyhub.py
eahub/profiles/migrations/0008_profile_slug.py
eahub/profiles/models.py
eahub/requirements.txt

This doesn't actually enable any redirects yet, but it does ensure that we can do so later without worrying about conflicts, even if people register new accounts in the meantime with what would otherwise be conflicting names.
Part of #428.

 Import user redirect aliases from legacy Hub

---

eahub/config/urls.py
eahub/localgroups/urls.py
eahub/profiles/urls.py

Personally I prefer not having a trailing slash, but a bunch of other Django stuff we're using includes them, and inconsistencies here are likely to lead to subtle bugs.
URLs with file extensions (favicon.ico and robots933456.txt) don't have trailing slashes.
Fixes: #518

Use trailing slashes consistently in URLs

---

eahub/templates/eahub/group.html

I noticed that master branch and product are out of sync since [there is an error in production that doesn't show up on master](https://github.com/rtcharity/eahub.org/issues/634). This error was fixed in [this PR](https://github.com/rtcharity/eahub.org/pull/574). 
Furthermore, on master, I'm getting 404s when reporting groups as inactive or claiming them. However, this error doesn't show up in production. Again, this is because master and production are out of sync. This PR fixes the code that causes the error in master. Once this PR is merged, we should deploy.

fix url for group actions

---

eahub/profiles/migrations/0009_profile_validate_sluggable_name.py

The actual code doesn't need this, but the migration generator cares about it.

Commit pending migration

---

eahub/profiles/forms.py
eahub/profiles/migrations/0010_remove_profile_subscribed_to_email_updates.py
eahub/profiles/models.py
eahub/templates/eahub/edit_profile.html

Mailchimp will be handling this from now on instead.
First deploy this to prod, then move the existing subscription data to Mailchimp, and only then run the migration.
Signed-off-by: Taymon A. Beal <taymon@google.com>

Remove subscribed_to_email_updates from profiles

---

eahub/base/static/scripts/main.js
eahub/templates/base.html

fixes #590: Menu (navbar) now disappears when one moves cursor away from menu. So there is no need to click anywhere to make it disappear
fixes #212: As menu disappears when one moves cursor away from menu, edit buttons are no longer covered up by the menu's div and can be accessed.

Make menu disappear when moving cursor away

---

README.md

We no longer require this.
Fixes: #636

Remove references to DCO from README

---

eahub/templates/base.html

Mirroring the behaviour of [PR 781](https://github.com/rtcharity/eahub.org/pull/781)
If a user was on a page which required authentication, then logging out now redirects to the log in page.

Redirect to previous page after user logs out

---

eahub/base/views.py
eahub/localgroups/migrations/0004_localgroup_is_public.py
eahub/localgroups/models.py
eahub/localgroups/views.py
eahub/profiles/forms.py

The permissions are not sophisticated. A group can be either public or private. From a user's perspective, private groups don't exist; users can't create private groups, change the privacy setting of groups, or see, modify, or be aware of the existence of a group that's private, even if they're an organizer of it. Private groups do show up in the admin; admins can create private groups and can see and change everything about every group, including privacy settings.
Fixes: #776

Allow groups to be private

---

docker-compose.yml
eahub/base/static/styles/main.css
eahub/config/settings.py
eahub/profiles/forms.py
eahub/templates/account/signup.html
eahub/tests/signup_test.py

The threshold is currently set at 85%; we can adjust it up or down later if need be.
This involves creating a new site in the reCAPTCHA admin console; I currently own it.
The site key is in a separate setting from the v2 one, which I've already created in production, so we can switch back and forth with just code deployments if need be.
By default, reCAPTCHA is disabled in local development, but you can enable it by signing up for a site on localhost and adding your keys to your .env file.
I don't know how much this will help, but it may be worth a try.

Migrate to reCAPTCHA v3

---

eahub/base/static/styles/main.css
eahub/localgroups/rules.py
eahub/localgroups/views.py
eahub/profiles/forms.py
eahub/profiles/migrations/0014_profile_is_approved.py
eahub/profiles/models.py
eahub/profiles/rules.py
eahub/templates/eahub/edit_profile.html
eahub/templates/eahub/edit_profile_career.html
eahub/templates/eahub/edit_profile_cause_areas.html
eahub/templates/eahub/edit_profile_community.html
eahub/templates/eahub/groups.html
eahub/templates/eahub/profile.html
eahub/templates/eahub/profiles.html
eahub/templates/eahub/talentsearch.html

This includes a new migration. All profiles that already exist before the migration runs will be auto-approved. But any new ones created in the future will have to be approved manually.
Currently, approval works by going into the admin and checking the box for each individual profile.

Require approval for public profiles

---

eahub/base/admin.py
requirements.txt

You can now:
-   See right away whether a user's profile is approved.
-   Filter for only users with approved or unapproved profiles.
-   Click a user's name to see their profile in the admin.
-   Check multiple users and approve them all at once.
It should also be faster now with fewer redundant database queries.

Improve admin user list for easier mass approval

---

requirements.txt

All the upstream issues that originally necessitated the fork have been fixed.

Switch dependency from fork to upstream django-storages

---

Dockerfile

As discovered in the video conference with @michaltrzesimiech, @taymonbeal and @victor-yunenko, the error concerning webpack and collectstatic was caused by a misplaced ```echo``` statement in the ```Dockerfile```. I know that the plan was to re-implement our webpack solution, but I don't think anyone is currently working on this. I thus suggest that we for now just remove the ```echo``` to have a temporary fix. This is what this PR is for.
Not doing this would block any further development as the pipeline fails due to this error. While the current implementation is not the most elegant, I don't think we should wait for a new implementation, of which we don't know when it might come.

Remove echo statement to actually run collectstatic

---

eahub/profiles/forms.py
eahub/templates/eahub/edit_profile_community.html

Fixes a bug that throw a 500 whenever user went on the edit community page on their profile. Removes the "email is public" toggle from this form page, as this option already exists on the main edit profile page

Fix bug throwing 500 on edit profile community

---

eahub/profiles/models.py

to allign with migration file. Otherwise, when running "migrate", it is suggested that there are changes in the model not reflected in migration files.

Set default for emails_visible in profile model

---

eahub/localgroups/views.py
eahub/templates/emails/create_group.txt
eahub/templates/emails/delete_group.txt
eahub/templates/emails/update_group.txt

Sends emails to groups@effectivealtruism.org and lean@eahub.org on the following actions:
- Group is created  
- Group is updated
- Group is deleted
The emails look as follows (emails addresses are dummy emails, not real ones):
**How to QA**:
Create, update and delete a group and check whether 
1) The actions are successful (group created, updated, deleted)  
2) Emails received at localhost:8001

931 email notifications on edits

---

eahub/base/utils.py
eahub/localgroups/admin.py
eahub/localgroups/models.py
eahub/profiles/admin.py
eahub/profiles/models.py

Gives admins ability to download groups and profiles as csvs. Closes #777 
How to check functionality in development mode:
- Make sure you have at least one profile and one localgroup in your local database
- Get password for admin account by 
- clicking on "send me password reset email" on login page
- request for "admin@example.com"
- go to localhost:8001 to check emails
- go on password reset link in last email received
- login as admin with new account
- go to localhost:8000/admin
- go to profiles and localgroups tabs respectively and choose "export as csv" from actions

777 export group data from admin panel

---

eahub/base/static/global/js/navbar.js
eahub/base/static/global/styles/main.css
eahub/templates/base.html
eahub/templates/eahub/index.html

* Changes the style of the existing navbar to look as much as possible as the one on the new profiles page: https://eahub-stage.us.aldryn.io/profiles/. 
* It wasn't possible to use the same code as the one on the new profiles page as this is using bootstrap 5, but we're using bootstrap 3 on all other, "old" pages. As it's not the same code, the styles aren't identical, but just similar. To achieve identical styles would have taken a lot more time, and I don't think it's worth the effort.  
* This MR is a hack to make the UX not too inconsistent between new profiles page and the other pages, but we should implement the same navbar on all pages, implying that we should replace bootstrap 3 with 5  
* When testing mobile/desktop, make sure to refresh after switching back and force between …

1007 update navbar

---

eahub/localgroups/admin.py
eahub/localgroups/models.py
eahub/tests/test_localgroups_admin.py

* Fixes issues with group data import to address #989:  
* Issue that prevented groups from being updated (rather than newly added) caused by utf-8 BOM  
* Issue with importing group types (required creating own Widget for Enums)  
* Maps organiser names to profiles      
* Adds functionality for marking selected groups in admin panel public/not_public
* Adds DateRangeFilter for "last_updated" field

989 group data import fix

---

eahub/profiles/models.py

This reverts commit 0613eb2b0698ef355cad01f03dcad87af4931019 as it fixed the update data, but created wrong rendering of profile data on search

Revert "fix bug with enums (#1052)"

---

README.md
eahub/base/utils.py
eahub/localgroups/admin.py
eahub/localgroups/models.py
eahub/profiles/admin.py
eahub/profiles/models.py
eahub/tests/test_localgroups_admin.py
eahub/tests/test_localgroups_model.py
eahub/tests/test_profile_model.py

* Adds filter of users by giving pledge to admin panel  
* Adds filter of users by whether there email is visible to admin panel  
* Fixes bug with profiles export such that values where not matched to correct columns  
Triggered by request from GWWC to get a list of all public users who have taken the pledge. Adding filter to email since we don't want to share hidden emails  
closes #1049

Allow filtering users by giving pledge
